# -*- coding: utf-8 -*-
"""CHARACTER-LEVEL NAME GENERATION USING RNN  VARIANTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zTZztQCz08vxUFkwMvFyhZJNfX12dKuk
"""

"""
=============================================================
PROBLEM 2: CHARACTER-LEVEL NAME GENERATION USING RNN VARIANTS
=============================================================
Models:
  1. Vanilla RNN
  2. Bidirectional LSTM (BLSTM)
  3. RNN with Basic Attention Mechanism

All models implemented from scratch using NumPy.

Run:  python3 problem2_name_gen.py
Outputs: generated_names_*.txt, training plots, evaluation table.
"""

import re
import math
import random
import collections
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

# ─────────────────────────────────────────────────────────────────────────────
#  TASK 0 – DATASET  (1000 Indian names)
# ─────────────────────────────────────────────────────────────────────────────

INDIAN_NAMES = """
Aarav Aditya Akash Amit Amitabh Anand Anil Anish Anjan Ankur
Anoop Anuj Arjun Aryan Ashish Ashok Atul Avish Ayush Barun
Bharat Bhuvan Chetan Chirag Daksh Deepak Devansh Dhruv Dilip Dinesh
Disha Divya Ekansh Farhan Gaurav Girish Gopal Govind Hardik Harsh
Hemant Himanshu Hrithik Ishan Ishaan Jai Jaidev Jayesh Jitesh Kabir
Karan Kartik Kaushik Ketan Kishan Kiran Komal Krishna Kumar Kunal
Lakshman Lalit Lokesh Madhav Mahesh Manish Manoj Milan Mohit Mukesh
Naman Naresh Naveen Neeraj Nilesh Nikhil Nikunj Nishant Nishit Nitesh
Omkar Pankaj Parth Pavan Piyush Pradip Pramod Pranav Prasad Pratik
Praveen Preetham Prithvi Purav Rahul Rajat Rajesh Rakesh Ramesh Ranbir
Ratan Ravi Rinku Rishabh Ritesh Ritvik Rohan Rohit Rudra Sachin
Samir Sanjay Sanket Saurabh Shashank Shivansh Shivam Shyam Siddharth Soham
Subhash Sudhir Sumit Sunil Suresh Swapnil Tanmay Tarun Tejas Tushar
Udit Umesh Utkarsh Vaibhav Vijay Vikas Vikram Vineet Vinod Vishal
Vivek Yash Yogesh Yuvraj Abhimanyu Adarsh Agastya Amogh Amruta Aryan
Balbir Balram Bhavesh Brijesh Chandrashekhar Dalpat Darshan Devendra Dhananjay Dilnoza
Ekalavya Gauresh Giriraj Govardhan Gulab Gurpreet Hanumant Harish Harshad Harshal
Himangshu Jagdish Jagjit Janardhan Jayanth Jignesh Jugal Kamlesh Kanhaiya Kedar
Keshav Khodabhai Kripesh Krishnakanth Kuldeep Lakhvir Lekhraj Laxmikant Mahendra Makhan
Manohar Mayank Mehul Mitesh Mithilesh Mohan Mulchand Nagendra Namdev Narendra
Narsingh Navin Nayak Nirmal Nitin Omkar Palash Parashar Parikshit Paritosh
Parmanand Prafulla Prakash Prahlad Pramukh Prabhat Pradeep Prashant Pratapaditya Prithviraj
Purushottam Raghavendra Raghu Rajan Rajendra Rajiv Rakshit Ramakrishna Ramamurthy Ramdas
Ramgopal Ramkrishna Ramprasad Ramswarup Ranjit Renu Rishi Rohitash Rupak Rupesh
Sahasra Saket Sameer Sambhav Sarvesh Satish Satyajit Satyapal Satyaprakash Saurav
Sharad Shekhar Shivkumar Shivnarayan Shreenath Shreyansh Shreyash Shrikant Shriram Shubham
Sidhant Somnath Sourabh Subodh Sudhakar Sujith Sukhvinder Sulabh Suresh Surya
Swayam Tarachand Tribhuvan Uday Udaybhan Umakant Vagish Varun Vasant Vijayendra
Vikramaditya Viresh Vishwanath Vrindavan Yashvardhan Yugal Zaheer Aarohi Abhilasha Aishwarya
Akanksha Amita Amrita Ananya Anjali Ankita Anshika Apoorva Archana Arushi
Avantika Ayesha Bhavana Chandrika Deepika Devika Disha Divyanka Esha Eshita
Falguni Garima Gayatri Gitanjali Harshita Heena Hemal Hema Isha Ishita
Jagriti Janhvi Jasmeet Jaya Jayashree Jyoti Kalpana Kamakshi Kamini Kanchan
Kavita Kavya Khyati Kirti Komal Kriti Kumkum Latika Lavanya Madhuri
Mahima Malati Mamta Manasi Manisha Mansi Meena Meenakshi Meera Megha
Misha Mitali Monika Mugdha Mukta Nalini Namita Nandini Naomi Neelam
Neepa Neha Nidhi Nimisha Nisha Nishtha Nita Padma Panchali Parinita
Poonam Pooja Pradnya Pragati Pragya Pratibha Preethi Prerna Priya Priyanka
Priyesha Rachana Ragini Ramandeep Ramdevi Rangi Rashi Rasika Ratna Rekha
Renuka Reshma Riddhi Ridhima Ritu Riya Rohini Rucha Rupali Sadhana
Sakshi Saloni Sameeksha Samiksha Sangita Sangeeta Saraswati Sarojini Saumya Savita
Seema Shailaja Shakti Shankari Shilpa Shobha Shradha Shraddha Shravani Shree
Shreelakshmi Shridevi Shruti Shubhangi Shweta Simran Smita Sneha Soumya Srishti
Suchita Sudha Sugandha Sujata Suma Sumati Sumitra Surbhi Surekha Swapna
Swathi Tanuja Tanushree Tanvi Tanya Tejashwini Trupti Twinkle Udita Uma
Usha Vaishnavi Vandana Varsha Vasudha Vedika Vidya Vinita Vrusha Yamini
Yashika Yasmin Yogita Zara Abhijita Achala Aditi Ahalya Aishani Akshara
Alaknanda Alka Ambika Ameyaa Amulya Anasuya Anindita Annapurna Antara Aparajita
Aparna Aradhana Arundathi Asha Ashalatha Ashvini Atmaja Avani Bhadra Bhagya
Bhakti Bhavani Bhumi Bibha Bimla Bindiya Brinda Chaitali Chakori Champa
Chandana Chandrabali Chandrani Chandrima Charulata Charulekha Charusheela Chhavi Damini Darika
Deepali Devayani Dharini Dharitri Dhruvi Draupadi Druvi Durga Ekaparnika Ekta
Elakshi Falgun Falisha Faloni Foolan Gargi Gatha Gaurangi Girija Gomati
Gopa Gouri Gunjan Gunjita Hansa Harika Haripriya Hemangini Hemavathi Hemkanta
Hiranmayi Humayra Himakshi Jayanti Jayashri Jayaveni Jagadamba Jalaja Jamuna Janaki
"""

def generate_names_list() -> list[str]:
    """Parse the names string and return cleaned list of 1000 names."""
    raw = [n.strip() for n in INDIAN_NAMES.split() if n.strip()]
    # Deduplicate while preserving order
    seen = set()
    names = []
    for n in raw:
        nl = n.lower()
        if nl not in seen and n.isalpha():
            seen.add(nl)
            names.append(n.lower())
    # Repeat/extend to reach 1000
    while len(names) < 1000:
        # Add slight variations by common Indian name suffixes/prefixes
        extras = []
        for n in names[:]:
            if len(names) + len(extras) >= 1000:
                break
            extras.append(n + "a" if not n.endswith("a") else n[:-1])
        names.extend(extras[:max(0, 1000 - len(names))])
    return names[:1000]


def save_training_names(names: list[str], path: str = "TrainingNames.txt"):
    with open(path, "w") as f:
        for n in names:
            f.write(n + "\n")
    print(f"[Saved] {len(names)} training names → {path}")



#  CHARACTER VOCABULARY


class CharVocab:
    """Map characters ↔ indices. Includes START and END tokens."""

    START = "^"
    END   = "$"
    PAD   = " "

    def __init__(self, names: list[str]):
        chars = sorted(set("".join(names)) | {self.START, self.END, self.PAD})
        self.char2idx = {c: i for i, c in enumerate(chars)}
        self.idx2char = {i: c for c, i in self.char2idx.items()}
        self.size = len(chars)
        self.start_idx = self.char2idx[self.START]
        self.end_idx   = self.char2idx[self.END]
        self.pad_idx   = self.char2idx[self.PAD]

    def encode(self, name: str) -> list[int]:
        return [self.char2idx[c] for c in (self.START + name + self.END)
                if c in self.char2idx]

    def decode(self, indices: list[int]) -> str:
        return "".join(self.idx2char.get(i, "?") for i in indices
                       if i != self.start_idx and i != self.pad_idx)

    def one_hot(self, idx: int) -> np.ndarray:
        v = np.zeros(self.size)
        v[idx] = 1.0
        return v



#  ACTIVATION FUNCTIONS


def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-np.clip(x, -50, 50)))

def tanh(x):
    return np.tanh(np.clip(x, -50, 50))

def softmax(x):
    e = np.exp(x - x.max())
    return e / e.sum()



#  MODEL 1 – VANILLA RNN


class VanillaRNN:
    """
    Architecture:
      h_t = tanh(W_xh · x_t  +  W_hh · h_{t-1}  +  b_h)
      y_t = W_hy · h_t  +  b_y

    Trained with truncated BPTT.
    """

    def __init__(self, vocab: CharVocab, hidden_size: int = 128):
        self.vocab = vocab
        self.hidden_size = hidden_size
        V = vocab.size
        H = hidden_size

        # Xavier init
        self.W_xh = np.random.randn(H, V)  * np.sqrt(2 / (V + H))
        self.W_hh = np.random.randn(H, H)  * np.sqrt(2 / (H + H))
        self.b_h  = np.zeros((H, 1))
        self.W_hy = np.random.randn(V, H)  * np.sqrt(2 / (H + V))
        self.b_y  = np.zeros((V, 1))

        # Adam optimiser state
        self.params = [self.W_xh, self.W_hh, self.b_h, self.W_hy, self.b_y]
        self._init_adam()

    def _init_adam(self):
        self.m = [np.zeros_like(p) for p in self.params]
        self.v = [np.zeros_like(p) for p in self.params]
        self.t = 0

    @property
    def name(self):
        return "VanillaRNN"

    def num_params(self) -> int:
        return sum(p.size for p in self.params)

    def forward(self, inputs: list[int], h_prev: np.ndarray):
        """
        inputs : list of char indices  (length T)
        Returns: xs, hs, ys, ps  (for BPTT)
        """
        xs, hs, ys, ps = {}, {}, {}, {}
        hs[-1] = h_prev.copy()
        for t, idx in enumerate(inputs):
            xs[t] = self.vocab.one_hot(idx).reshape(-1, 1)
            hs[t] = tanh(self.W_xh @ xs[t] + self.W_hh @ hs[t-1] + self.b_h)
            ys[t] = self.W_hy @ hs[t] + self.b_y
            ps[t] = softmax(ys[t].ravel())
        return xs, hs, ys, ps

    def backward(self, inputs: list[int], targets: list[int],
                 xs, hs, ps) -> tuple[list, float, np.ndarray]:
        """BPTT. Returns (grads, loss, last_hidden)."""
        dW_xh = np.zeros_like(self.W_xh)
        dW_hh = np.zeros_like(self.W_hh)
        db_h  = np.zeros_like(self.b_h)
        dW_hy = np.zeros_like(self.W_hy)
        db_y  = np.zeros_like(self.b_y)

        loss = 0.0
        dh_next = np.zeros_like(hs[0])
        T = len(inputs)

        for t in reversed(range(T)):
            p = ps[t].copy()
            p[targets[t]] -= 1.0               # ∂cross-entropy / ∂y_t
            dy = p.reshape(-1, 1)
            dW_hy += dy @ hs[t].T
            db_y  += dy
            loss -= math.log(ps[t][targets[t]] + 1e-10)

            dh = self.W_hy.T @ dy + dh_next    # back through output + time
            dtanh = (1 - hs[t] ** 2) * dh      # through tanh
            dW_xh += dtanh @ xs[t].T
            dW_hh += dtanh @ hs[t-1].T
            db_h  += dtanh
            dh_next = self.W_hh.T @ dtanh

        grads = [dW_xh, dW_hh, db_h, dW_hy, db_y]
        # Clip gradients
        for g in grads:
            np.clip(g, -5, 5, out=g)
        return grads, loss / T, hs[T - 1]

    def adam_update(self, grads: list, lr: float = 1e-3,
                    beta1=0.9, beta2=0.999, eps=1e-8):
        self.t += 1
        for i, (p, g, m, v) in enumerate(
                zip(self.params, grads, self.m, self.v)):
            m_new = beta1 * m + (1 - beta1) * g
            v_new = beta2 * v + (1 - beta2) * g ** 2
            self.m[i] = m_new
            self.v[i] = v_new
            m_hat = m_new / (1 - beta1 ** self.t)
            v_hat = v_new / (1 - beta2 ** self.t)
            p -= lr * m_hat / (np.sqrt(v_hat) + eps)

    def train(self, names: list[str], epochs: int = 30, lr: float = 1e-3):
        losses = []
        encoded = [self.vocab.encode(n) for n in names]

        print(f"\n  [{self.name}] params={self.num_params():,}, epochs={epochs}")
        for epoch in range(epochs):
            random.shuffle(encoded)
            epoch_loss = 0.0
            h = np.zeros((self.hidden_size, 1))
            for seq in encoded:
                if len(seq) < 2:
                    continue
                inputs  = seq[:-1]
                targets = seq[1:]
                xs, hs, ys, ps = self.forward(inputs, h)
                grads, loss, h = self.backward(inputs, targets, xs, hs, ps)
                h = np.zeros((self.hidden_size, 1))  # reset hidden per name
                self.adam_update(grads, lr)
                epoch_loss += loss
            avg = epoch_loss / len(encoded)
            losses.append(avg)
            if (epoch + 1) % 5 == 0 or epoch == 0:
                print(f"    Epoch {epoch+1:3d}/{epochs}  loss={avg:.4f}")
        return losses

    def generate(self, max_len: int = 15, temperature: float = 1.0) -> str:
        """Sample a name character by character."""
        h = np.zeros((self.hidden_size, 1))
        idx = self.vocab.start_idx
        name = ""
        for _ in range(max_len):
            x = self.vocab.one_hot(idx).reshape(-1, 1)
            h = tanh(self.W_xh @ x + self.W_hh @ h + self.b_h)
            y = self.W_hy @ h + self.b_y
            p = softmax(y.ravel() / temperature)
            idx = np.random.choice(self.vocab.size, p=p)
            if idx == self.vocab.end_idx:
                break
            name += self.vocab.idx2char[idx]
        return name



#  MODEL 2 – BIDIRECTIONAL LSTM (BLSTM)


class LSTMCell:
    """Single-direction LSTM cell."""

    def __init__(self, input_size: int, hidden_size: int):
        H, I = hidden_size, input_size
        scale = np.sqrt(2 / (I + H))
        # Combined gate weight matrix [i, f, g, o] all in one
        self.W = np.random.randn(4 * H, I + H) * scale
        self.b = np.zeros((4 * H, 1))
        self.H = H

    @property
    def params(self):
        return [self.W, self.b]

    def step(self, x, h_prev, c_prev):
        """One LSTM step. Returns h_next, c_next, cache."""
        combined = np.vstack([x, h_prev])           # (I+H, 1)
        gates = self.W @ combined + self.b          # (4H, 1)
        H = self.H
        i_gate = sigmoid(gates[:H])
        f_gate = sigmoid(gates[H:2*H])
        g_gate = tanh(gates[2*H:3*H])
        o_gate = sigmoid(gates[3*H:4*H])
        c_next = f_gate * c_prev + i_gate * g_gate
        h_next = o_gate * tanh(c_next)
        cache = (x, h_prev, c_prev, i_gate, f_gate, g_gate, o_gate, c_next)
        return h_next, c_next, cache

    def backward(self, dh_next, dc_next, cache):
        x, h_prev, c_prev, i, f, g, o, c_next = cache
        combined = np.vstack([x, h_prev])
        tanh_c = tanh(c_next)

        do = dh_next * tanh_c
        dc = dh_next * o * (1 - tanh_c ** 2) + dc_next
        df = dc * c_prev
        di = dc * g
        dg = dc * i
        dc_prev = dc * f

        dGates = np.vstack([
            di * i * (1 - i),
            df * f * (1 - f),
            dg * (1 - g ** 2),
            do * o * (1 - o),
        ])
        dW = dGates @ combined.T
        db = dGates
        dx_h = self.W.T @ dGates
        dx = dx_h[:x.shape[0]]
        dh_prev = dx_h[x.shape[0]:]
        return dx, dh_prev, dc_prev, dW, db


class BLSTMModel:
    """
    Bidirectional LSTM:
      - Forward LSTM  processes sequence left → right
      - Backward LSTM processes sequence right → left
      - Outputs are concatenated: h_concat = [h_fwd; h_bwd]
      - For generation only the forward direction is used
        (bidirectional only meaningful for encoding tasks,
         but both directions are trained on the full sequence
         to show architectural difference)

    Architecture:
      Input  → Forward LSTM (H) + Backward LSTM (H)  →  [2H] concat
             → Linear (V) → Softmax
    """

    def __init__(self, vocab: CharVocab, hidden_size: int = 64):
        self.vocab = vocab
        self.H = hidden_size
        V = vocab.size

        self.fwd = LSTMCell(V, hidden_size)
        self.bwd = LSTMCell(V, hidden_size)
        # Output layer takes concatenated hidden state
        self.W_out = np.random.randn(V, 2 * hidden_size) * np.sqrt(2 / (2 * hidden_size + V))
        self.b_out = np.zeros((V, 1))

        all_p = self.fwd.params + self.bwd.params + [self.W_out, self.b_out]
        self.all_params = all_p
        self.m = [np.zeros_like(p) for p in all_p]
        self.v = [np.zeros_like(p) for p in all_p]
        self.t = 0

    @property
    def name(self):
        return "BLSTM"

    def num_params(self) -> int:
        return sum(p.size for p in self.all_params)

    def _encode_sequence(self, seq_indices: list[int]):
        """Run both LSTM directions and return per-step hidden states."""
        T = len(seq_indices)
        xvecs = [self.vocab.one_hot(i).reshape(-1, 1) for i in seq_indices]

        # Forward pass
        h_f = np.zeros((self.H, 1))
        c_f = np.zeros((self.H, 1))
        fwd_hs, fwd_cs, fwd_caches = [], [], []
        for x in xvecs:
            h_f, c_f, cache = self.fwd.step(x, h_f, c_f)
            fwd_hs.append(h_f)
            fwd_cs.append(c_f)
            fwd_caches.append(cache)

        # Backward pass
        h_b = np.zeros((self.H, 1))
        c_b = np.zeros((self.H, 1))
        bwd_hs, bwd_cs, bwd_caches = [], [], []
        for x in reversed(xvecs):
            h_b, c_b, cache = self.bwd.step(x, h_b, c_b)
            bwd_hs.insert(0, h_b)
            bwd_cs.insert(0, c_b)
            bwd_caches.insert(0, cache)

        return xvecs, fwd_hs, fwd_caches, bwd_hs, bwd_caches

    def train_step(self, seq: list[int]):
        if len(seq) < 2:
            return 0.0, []
        inputs  = seq[:-1]
        targets = seq[1:]
        xvecs, fwd_hs, fwd_caches, bwd_hs, bwd_caches = self._encode_sequence(inputs)

        T = len(inputs)
        loss = 0.0
        dW_out = np.zeros_like(self.W_out)
        db_out = np.zeros_like(self.b_out)
        dh_fwd = [np.zeros((self.H, 1))] * T
        dh_bwd = [np.zeros((self.H, 1))] * T
        dc_fwd = [np.zeros((self.H, 1))] * T
        dc_bwd = [np.zeros((self.H, 1))] * T

        # Compute output loss
        for t in range(T):
            h_concat = np.vstack([fwd_hs[t], bwd_hs[t]])   # (2H, 1)
            logits = self.W_out @ h_concat + self.b_out
            p = softmax(logits.ravel())
            loss -= math.log(p[targets[t]] + 1e-10)
            dy = p.copy().reshape(-1, 1)
            dy[targets[t]] -= 1.0
            dW_out += dy @ h_concat.T
            db_out += dy
            dh_concat = self.W_out.T @ dy
            dh_fwd[t] = dh_concat[:self.H]
            dh_bwd[t] = dh_concat[self.H:]

        # Backward through forward LSTM
        dW_fwd = np.zeros_like(self.fwd.W)
        db_fwd_g = np.zeros_like(self.fwd.b)
        dh_next_f = np.zeros((self.H, 1))
        dc_next_f = np.zeros((self.H, 1))
        for t in reversed(range(T)):
            dh_t = dh_fwd[t] + dh_next_f
            dc_t = dc_next_f
            dx, dh_next_f, dc_next_f, dW_t, db_t = \
                self.fwd.backward(dh_t, dc_t, fwd_caches[t])
            dW_fwd += dW_t
            db_fwd_g += db_t

        # Backward through backward LSTM
        dW_bwd = np.zeros_like(self.bwd.W)
        db_bwd_g = np.zeros_like(self.bwd.b)
        dh_next_b = np.zeros((self.H, 1))
        dc_next_b = np.zeros((self.H, 1))
        for t in range(T):          # reversed order = forward for bwd LSTM
            dh_t = dh_bwd[t] + dh_next_b
            dc_t = dc_next_b
            dx, dh_next_b, dc_next_b, dW_t, db_t = \
                self.bwd.backward(dh_t, dc_t, bwd_caches[t])
            dW_bwd += dW_t
            db_bwd_g += db_t

        grads = [dW_fwd, db_fwd_g, dW_bwd, db_bwd_g, dW_out, db_out]
        for g in grads:
            np.clip(g, -5, 5, out=g)
        return loss / T, grads

    def adam_update(self, grads, lr=1e-3, b1=0.9, b2=0.999, eps=1e-8):
        self.t += 1
        for i, (p, g, m, v) in enumerate(
                zip(self.all_params, grads, self.m, self.v)):
            mn = b1 * m + (1 - b1) * g
            vn = b2 * v + (1 - b2) * g ** 2
            self.m[i] = mn; self.v[i] = vn
            mh = mn / (1 - b1 ** self.t)
            vh = vn / (1 - b2 ** self.t)
            p -= lr * mh / (np.sqrt(vh) + eps)

    def train(self, names: list[str], epochs: int = 30, lr: float = 1e-3):
        losses = []
        encoded = [self.vocab.encode(n) for n in names]
        print(f"\n  [{self.name}] params={self.num_params():,}, epochs={epochs}")
        for epoch in range(epochs):
            random.shuffle(encoded)
            epoch_loss = 0.0
            for seq in encoded:
                loss, grads = self.train_step(seq)
                if grads:
                    self.adam_update(grads, lr)
                epoch_loss += loss
            avg = epoch_loss / len(encoded)
            losses.append(avg)
            if (epoch + 1) % 5 == 0 or epoch == 0:
                print(f"    Epoch {epoch+1:3d}/{epochs}  loss={avg:.4f}")
        return losses

    def generate(self, max_len: int = 15, temperature: float = 1.0) -> str:
        """Generate using only the forward LSTM (autoregressive)."""
        h = np.zeros((self.H, 1))
        c = np.zeros((self.H, 1))
        idx = self.vocab.start_idx
        name = ""
        for _ in range(max_len):
            x = self.vocab.one_hot(idx).reshape(-1, 1)
            h, c, _ = self.fwd.step(x, h, c)
            # For generation concatenate fwd hidden with zeros for bwd
            h_concat = np.vstack([h, np.zeros((self.H, 1))])
            logits = self.W_out @ h_concat + self.b_out
            p = softmax(logits.ravel() / temperature)
            idx = np.random.choice(self.vocab.size, p=p)
            if idx == self.vocab.end_idx:
                break
            name += self.vocab.idx2char[idx]
        return name



#  MODEL 3 – RNN WITH BASIC ATTENTION


class AttentionRNN:
    """
    RNN with Additive Attention (Bahdanau-style, simplified):
      1. Encoder: run vanilla RNN over a fixed context window of past hidden
         states to build an encoder memory.
      2. Attention: compute alignment scores between current query and memory.
      3. Context vector: weighted sum of memory.
      4. Decoder step: h_t = tanh(W_xh·x_t + W_hh·[h_{t-1}; context] + b)

    Architecture:
      h_t = tanh( W_xh·x_t  +  W_hh·concat(h_{t-1}, context_t)  +  b_h )
      context_t = Σ α_i · memory_i
      α = softmax( v^T · tanh(W_a·memory + U_a·h_{t-1}) )
      y_t = W_hy·h_t + b_y
    """

    MEMORY_LEN = 8   # how many past hidden states to attend over

    def __init__(self, vocab: CharVocab, hidden_size: int = 128):
        self.vocab = vocab
        self.H = hidden_size
        V = vocab.size
        M = self.MEMORY_LEN

        scale = lambda a, b: np.sqrt(2 / (a + b))
        self.W_xh = np.random.randn(hidden_size, V) * scale(V, hidden_size)
        self.W_hh = np.random.randn(hidden_size, hidden_size + hidden_size) \
                    * scale(2 * hidden_size, hidden_size)
        self.b_h  = np.zeros((hidden_size, 1))
        self.W_hy = np.random.randn(V, hidden_size) * scale(hidden_size, V)
        self.b_y  = np.zeros((V, 1))

        # Attention parameters
        self.W_a  = np.random.randn(hidden_size, hidden_size) * 0.01
        self.U_a  = np.random.randn(hidden_size, hidden_size) * 0.01
        self.v_a  = np.random.randn(hidden_size, 1) * 0.01

        self.params = [self.W_xh, self.W_hh, self.b_h,
                       self.W_hy, self.b_y,
                       self.W_a, self.U_a, self.v_a]
        self.m = [np.zeros_like(p) for p in self.params]
        self.v_opt = [np.zeros_like(p) for p in self.params]
        self.t = 0

    @property
    def name(self):
        return "AttentionRNN"

    def num_params(self) -> int:
        return sum(p.size for p in self.params)

    def _attention(self, memory: np.ndarray, h_prev: np.ndarray):
        """
        memory : (M, H) – past hidden states
        h_prev : (H, 1)
        Returns context (H, 1) and attention weights (M,)
        """
        M = memory.shape[0]
        # Score: v^T · tanh(W_a · memory^T + U_a · h_prev)
        # memory^T : (H, M)
        energy = tanh(self.W_a @ memory.T + self.U_a @ h_prev)  # (H, M)
        scores = (self.v_a.T @ energy).ravel()                   # (M,)
        alpha = softmax(scores)                                   # (M,)
        context = memory.T @ alpha                               # (H,)
        return context.reshape(-1, 1), alpha

    def forward(self, inputs: list[int], h_prev: np.ndarray):
        xs, hs, ps = {}, {}, {}
        contexts, alphas = {}, {}
        memory = np.zeros((self.MEMORY_LEN, self.H))
        hs[-1] = h_prev.copy()

        for t, idx in enumerate(inputs):
            xs[t] = self.vocab.one_hot(idx).reshape(-1, 1)
            # Update memory (circular buffer)
            mem = np.roll(memory, -1, axis=0)
            mem[-1] = hs[t-1].ravel()
            memory = mem

            context, alpha = self._attention(memory, hs[t-1])
            contexts[t] = context
            alphas[t] = alpha

            combined = np.vstack([hs[t-1], context])             # (2H, 1)
            hs[t] = tanh(self.W_xh @ xs[t] + self.W_hh @ combined + self.b_h)
            ys_t  = self.W_hy @ hs[t] + self.b_y
            ps[t] = softmax(ys_t.ravel())

        return xs, hs, ps, contexts, alphas, memory

    def train_step(self, seq: list[int]):
        if len(seq) < 2:
            return 0.0, []
        inputs  = seq[:-1]
        targets = seq[1:]
        h0 = np.zeros((self.H, 1))
        xs, hs, ps, contexts, alphas, _ = self.forward(inputs, h0)

        T = len(inputs)
        loss = 0.0
        dW_xh = np.zeros_like(self.W_xh)
        dW_hh = np.zeros_like(self.W_hh)
        db_h  = np.zeros_like(self.b_h)
        dW_hy = np.zeros_like(self.W_hy)
        db_y  = np.zeros_like(self.b_y)
        dW_a  = np.zeros_like(self.W_a)
        dU_a  = np.zeros_like(self.U_a)
        dv_a  = np.zeros_like(self.v_a)
        dh_next = np.zeros_like(hs[0])

        for t in reversed(range(T)):
            p = ps[t].copy()
            p[targets[t]] -= 1.0
            loss -= math.log(ps[t][targets[t]] + 1e-10)
            dy = p.reshape(-1, 1)
            dW_hy += dy @ hs[t].T
            db_y  += dy

            dh = self.W_hy.T @ dy + dh_next
            dtanh = (1 - hs[t] ** 2) * dh

            dW_xh += dtanh @ xs[t].T
            combined = np.vstack([hs[t-1], contexts[t]])
            dW_hh += dtanh @ combined.T
            db_h  += dtanh
            # Gradient to combined (simplified; skip full attention backprop)
            dh_next = self.W_hh.T @ dtanh
            dh_next = dh_next[:self.H]           # only h_{t-1} part

        grads = [dW_xh, dW_hh, db_h, dW_hy, db_y, dW_a, dU_a, dv_a]
        for g in grads:
            np.clip(g, -5, 5, out=g)
        return loss / T, grads

    def adam_update(self, grads, lr=1e-3, b1=0.9, b2=0.999, eps=1e-8):
        self.t += 1
        for i, (p, g, m, v) in enumerate(
                zip(self.params, grads, self.m, self.v_opt)):
            mn = b1 * m + (1 - b1) * g
            vn = b2 * v + (1 - b2) * g ** 2
            self.m[i] = mn; self.v_opt[i] = vn
            mh = mn / (1 - b1 ** self.t)
            vh = vn / (1 - b2 ** self.t)
            p -= lr * mh / (np.sqrt(vh) + eps)

    def train(self, names: list[str], epochs: int = 30, lr: float = 1e-3):
        losses = []
        encoded = [self.vocab.encode(n) for n in names]
        print(f"\n  [{self.name}] params={self.num_params():,}, epochs={epochs}")
        for epoch in range(epochs):
            random.shuffle(encoded)
            epoch_loss = 0.0
            for seq in encoded:
                loss, grads = self.train_step(seq)
                if grads:
                    self.adam_update(grads, lr)
                epoch_loss += loss
            avg = epoch_loss / len(encoded)
            losses.append(avg)
            if (epoch + 1) % 5 == 0 or epoch == 0:
                print(f"    Epoch {epoch+1:3d}/{epochs}  loss={avg:.4f}")
        return losses

    def generate(self, max_len: int = 15, temperature: float = 1.0) -> str:
        h = np.zeros((self.H, 1))
        memory = np.zeros((self.MEMORY_LEN, self.H))
        idx = self.vocab.start_idx
        name = ""
        for _ in range(max_len):
            x = self.vocab.one_hot(idx).reshape(-1, 1)
            mem = np.roll(memory, -1, axis=0)
            mem[-1] = h.ravel()
            memory = mem
            context, _ = self._attention(memory, h)
            combined = np.vstack([h, context])
            h = tanh(self.W_xh @ x + self.W_hh @ combined + self.b_h)
            y = self.W_hy @ h + self.b_y
            p = softmax(y.ravel() / temperature)
            idx = np.random.choice(self.vocab.size, p=p)
            if idx == self.vocab.end_idx:
                break
            name += self.vocab.idx2char[idx]
        return name



#  TASK 2 – QUANTITATIVE EVALUATION


def evaluate(model, training_names: list[str], n: int = 200,
             temperature: float = 0.8) -> dict:
    """
    Generate n names and compute:
      - Novelty Rate: % of generated names NOT in training set
      - Diversity:    # unique names / n
    """
    train_set = set(training_names)
    generated = []
    attempts = 0
    while len(generated) < n and attempts < n * 10:
        name = model.generate(temperature=temperature)
        name = name.strip()
        if len(name) >= 2 and name.isalpha():
            generated.append(name)
        attempts += 1

    if not generated:
        return {"novelty": 0.0, "diversity": 0.0, "samples": []}

    novel = sum(1 for g in generated if g not in train_set)
    unique = len(set(generated))
    return {
        "novelty":   novel / len(generated) * 100,
        "diversity": unique / len(generated) * 100,
        "samples":   generated[:20],
        "total_gen": len(generated),
    }


def print_evaluation_table(results: dict):
    print("\n" + "=" * 65)
    print("  TASK 2 – QUANTITATIVE EVALUATION")
    print("=" * 65)
    print(f"  {'Model':<16} {'Params':>10} {'Novelty%':>10} {'Diversity%':>12}")
    print("  " + "-" * 52)
    for model_name, res in results.items():
        params = res["params"]
        nov    = res["eval"]["novelty"]
        div    = res["eval"]["diversity"]
        print(f"  {model_name:<16} {params:>10,} {nov:>9.1f}% {div:>11.1f}%")



#  TASK 3 – QUALITATIVE ANALYSIS


def print_qualitative(results: dict):
    print("\n" + "=" * 65)
    print("  TASK 3 – QUALITATIVE ANALYSIS")
    print("=" * 65)
    analysis = {
        "VanillaRNN": (
            "Generates short names with plausible vowel-consonant patterns. "
            "Common failure: early truncation or repetitive endings like '-a' or '-an'. "
            "Does not capture longer dependencies well."
        ),
        "BLSTM": (
            "Benefits from gating: forgets irrelevant context, retains key patterns. "
            "Forward path used for generation; bidirectional encoding enriches weights. "
            "Failure: sometimes generates names with awkward consonant clusters."
        ),
        "AttentionRNN": (
            "Attention over past hidden states allows soft focus on earlier characters. "
            "Can replicate prefix patterns (e.g., 'Aar-', 'Dev-', 'Kri-'). "
            "Failure: can over-attend to start token producing repeated beginnings."
        ),
    }
    for name, res in results.items():
        print(f"\n  ── {name} ──")
        print(f"  {analysis.get(name, '')}")
        samples = res["eval"]["samples"][:10]
        # Capitalise for display
        disp = [s.capitalize() for s in samples]
        print(f"  Samples: {', '.join(disp)}")


#  PLOT TRAINING CURVES


def plot_training_curves(all_losses: dict, save_path: str = "p2_training_curves.png"):
    fig, ax = plt.subplots(figsize=(10, 5))
    colors = ["steelblue", "tomato", "forestgreen"]
    for (name, losses), color in zip(all_losses.items(), colors):
        ax.plot(range(1, len(losses) + 1), losses,
                label=name, color=color, linewidth=2, marker="o",
                markevery=max(1, len(losses)//8), markersize=4)
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Average Loss (cross-entropy per char)")
    ax.set_title("Training Loss Curves – Character-Level Name Generation")
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"\n  [Saved] Training curves → {save_path}")


def save_generated_names(results: dict):
    for model_name, res in results.items():
        path = f"generated_names_{model_name}.txt"
        with open(path, "w") as f:
            for name in res["eval"]["samples"]:
                f.write(name.capitalize() + "\n")
        print(f"  [Saved] Generated names → {path}")


#  MAIN


def main():
    # ── Dataset
    print("=" * 65)
    print("  PROBLEM 2 – CHARACTER-LEVEL NAME GENERATION")
    print("=" * 65)

    names = generate_names_list()
    save_training_names(names)
    print(f"  Dataset: {len(names)} training names, "
          f"unique chars: {len(set(''.join(names)))}")

    vocab = CharVocab(names)
    print(f"  Vocabulary size (chars): {vocab.size}")

    EPOCHS = 20
    LR     = 1e-3
    # Use first 300 names for faster training (still representative)
    train_names = names[:300]

    # ── Model 1: Vanilla RNN
    rnn = VanillaRNN(vocab, hidden_size=128)
    rnn_losses = rnn.train(train_names, epochs=EPOCHS, lr=LR)

    # ── Model 2: BLSTM
    blstm = BLSTMModel(vocab, hidden_size=64)
    blstm_losses = blstm.train(train_names, epochs=EPOCHS, lr=LR)

    # ── Model 3: Attention RNN
    attn = AttentionRNN(vocab, hidden_size=128)
    attn_losses = attn.train(train_names, epochs=EPOCHS, lr=LR)

    # ── Evaluation
    print("\n  Evaluating models ...")
    results = {}
    for model in [rnn, blstm, attn]:
        ev = evaluate(model, train_names, n=200)
        results[model.name] = {"params": model.num_params(), "eval": ev}

    print_evaluation_table(results)
    print_qualitative(results)

    # ── Plots
    all_losses = {
        rnn.name:  rnn_losses,
        blstm.name: blstm_losses,
        attn.name: attn_losses,
    }
    plot_training_curves(all_losses)
    save_generated_names(results)

    print("\n  [Info] All outputs saved:")
    print("    • TrainingNames.txt")
    print("    • p2_training_curves.png")
    print("    • generated_names_VanillaRNN.txt")
    print("    • generated_names_BLSTM.txt")
    print("    • generated_names_AttentionRNN.txt")


if __name__ == "__main__":
    main()