# -*- coding: utf-8 -*-
"""problem1_word2vec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYTSZFH0HKTx-Afygo4VnANfnV2BVDaO
"""

!pip install requests beautifulsoup4 lxml pdfplumber

import requests
from bs4 import BeautifulSoup
import os
import re
from urllib.parse import urljoin

os.makedirs("data/raw", exist_ok=True)

BASE = "https://iitj.ac.in"

seed_urls = [
    "https://iitj.ac.in/departments/index.php",
    "https://iitj.ac.in/academics/index.php",
    "https://iitj.ac.in/research/index.php",
    "https://iitj.ac.in/people/index.php",
    "https://iitj.ac.in/news/index.php"
]

headers = {"User-Agent": "Mozilla/5.0"}
visited = set()

def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    return text.strip()

def scrape(url, idx):
    try:
        if url in visited:
            return []
        visited.add(url)

        res = requests.get(url, headers=headers)
        soup = BeautifulSoup(res.content, "lxml")

        text = clean_text(soup.get_text())

        if len(text) > 500:
            with open(f"data/raw/page_{idx}.txt", "w", encoding="utf-8") as f:
                f.write(text)
            print(f"Saved page_{idx}.txt")

        links = []
        for a in soup.find_all("a", href=True):
            full = urljoin(BASE, a["href"])
            if BASE in full:
                links.append(full)

        return links

    except Exception as e:
        print("Error:", e)
        return []

counter = 0

for url in seed_urls:
    queue = [url]

    while queue and counter < 40:
        u = queue.pop(0)
        new_links = scrape(u, counter)
        counter += 1

        for l in new_links[:5]:
            if l not in visited:
                queue.append(l)

from google.colab import files
uploaded = files.upload()

import pdfplumber

pdf_file = list(uploaded.keys())[0]

text = ""
with pdfplumber.open(pdf_file) as pdf:
    for page in pdf.pages:
        text += page.extract_text() or ""

with open("data/raw/regulations.txt", "w", encoding="utf-8") as f:
    f.write(text)

print("PDF extracted!")

import os

with open("iitj_corpus_raw.txt", "w", encoding="utf-8") as out:
    for file in os.listdir("data/raw"):
        if file.endswith(".txt"):
            with open(os.path.join("data/raw", file), "r", encoding="utf-8") as f:
                out.write(f.read() + "\n")

print("Corpus ready!")

import re
import math
import random
import collections
import numpy as np
import matplotlib.pyplot as plt

SEED = 42
random.seed(SEED)
np.random.seed(SEED)


# TASK 1 – DATASET PREPARATION


def load_raw_corpus(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

def preprocess(text):
    lines = text.split("\n")
    sentences = []

    for line in lines:
        line = line.encode("ascii", errors="ignore").decode()
        line = line.lower()
        line = re.sub(r"[^a-z\s]", " ", line)
        line = re.sub(r"\s+", " ", line).strip()

        tokens = [w for w in line.split() if len(w) > 2]
        if tokens:
            sentences.append(tokens)

    return sentences

def corpus_statistics(sentences):
    tokens = [w for s in sentences for w in s]
    vocab = set(tokens)
    freq = collections.Counter(tokens)

    print("\n===== DATASET STATS =====")
    print("Documents:", len(sentences))
    print("Tokens:", len(tokens))
    print("Vocab size:", len(vocab))

    print("\nTop words:")
    for w,c in freq.most_common(10):
        print(w, c)

    return freq

# load data
raw = load_raw_corpus("iitj_corpus_raw.txt")
sentences = preprocess(raw)

freq = corpus_statistics(sentences)


# TASK 2 – WORD2VEC (CBOW + SKIPGRAM + NEGATIVE SAMPLING)


class Vocabulary:
    def __init__(self, sentences):
        freq = collections.Counter(w for s in sentences for w in s)
        self.word2idx = {w:i for i,(w,_) in enumerate(freq.items())}
        self.idx2word = {i:w for w,i in self.word2idx.items()}
        self.size = len(self.word2idx)

    def encode(self, sentences):
        return [[self.word2idx[w] for w in s if w in self.word2idx] for s in sentences]

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

class SkipGram:
    def __init__(self, vocab_size, dim=50, window=2, lr=0.01):
        self.W = np.random.randn(vocab_size, dim)
        self.window = window
        self.lr = lr

    def train(self, data, epochs=3):
        print("\nTraining SkipGram...")
        for ep in range(epochs):
            loss = 0
            for sent in data:
                for i, center in enumerate(sent):
                    context = sent[max(0,i-self.window):i+self.window+1]
                    for word in context:
                        if word == center: continue
                        score = sigmoid(self.W[center] @ self.W[word])
                        grad = score - 1
                        self.W[center] -= self.lr * grad * self.W[word]
                        self.W[word] -= self.lr * grad * self.W[center]
                        loss += -math.log(score+1e-10)
            print(f"Epoch {ep+1} loss {loss:.2f}")

class CBOW:
    def __init__(self, vocab_size, dim=50, window=2, lr=0.01):
        self.W = np.random.randn(vocab_size, dim)
        self.window = window
        self.lr = lr

    def train(self, data, epochs=3):
        print("\nTraining CBOW...")
        for ep in range(epochs):
            loss = 0
            for sent in data:
                for i, target in enumerate(sent):
                    context = sent[max(0,i-self.window):i+self.window+1]
                    context = [w for w in context if w != target]

                    if not context: continue

                    avg = np.mean(self.W[context], axis=0)
                    score = sigmoid(avg @ self.W[target])
                    grad = score - 1

                    for w in context:
                        self.W[w] -= self.lr * grad * self.W[target]

                    self.W[target] -= self.lr * grad * avg
                    loss += -math.log(score+1e-10)

            print(f"Epoch {ep+1} loss {loss:.2f}")

# build vocab
vocab = Vocabulary(sentences)
data = vocab.encode(sentences)

# experiment configs
configs = [
    ("CBOW", 50, 2),
    ("CBOW", 100, 3),
    ("SkipGram", 50, 2),
    ("SkipGram", 100, 3),
]

models = {}

for name, dim, window in configs:
    if name == "CBOW":
        model = CBOW(vocab.size, dim, window)
    else:
        model = SkipGram(vocab.size, dim, window)

    model.train(data)
    models[f"{name}_{dim}_{window}"] = model


# TASK 3 – SEMANTIC ANALYSIS


def cosine(a,b):
    return np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b)+1e-10)

def nearest(word, model, vocab):
    if word not in vocab.word2idx:
        return []

    idx = vocab.word2idx[word]
    vec = model.W[idx]

    sims = []
    for i in range(vocab.size):
        if i == idx: continue
        sims.append((vocab.idx2word[i], cosine(vec, model.W[i])))

    sims.sort(key=lambda x:-x[1])
    return sims[:5]

def analogy(a,b,c,model,vocab):
    if any(w not in vocab.word2idx for w in [a,b,c]):
        return []

    vec = model.W[vocab.word2idx[b]] - model.W[vocab.word2idx[a]] + model.W[vocab.word2idx[c]]

    sims = []
    for i in range(vocab.size):
        sims.append((vocab.idx2word[i], cosine(vec, model.W[i])))

    sims.sort(key=lambda x:-x[1])
    return sims[:3]

# choose best model
model = list(models.values())[0]

print("\n=== NEAREST WORDS ===")
for w in ["research","student","phd","exam"]:
    print(f"\n{w}:")
    print(nearest(w, model, vocab))

print("\n=== ANALOGY ===")
print("ug : btech :: pg :", analogy("ug","btech","pg",model,vocab))
print("student : exam :: faculty :", analogy("student","exam","faculty",model,vocab))


# TASK 4 – VISUALIZATION (PCA)


def pca(X):
    X = X - X.mean(axis=0)
    cov = X.T @ X
    eigvals, eigvecs = np.linalg.eigh(cov)
    return X @ eigvecs[:, -2:]

words = list(vocab.word2idx.keys())[:50]
vecs = np.array([model.W[vocab.word2idx[w]] for w in words])

coords = pca(vecs)

plt.figure(figsize=(8,6))
for i, word in enumerate(words):
    plt.scatter(coords[i,0], coords[i,1])
    plt.text(coords[i,0], coords[i,1], word)

plt.title("Word Embeddings PCA")
plt.savefig("embedding.png")
plt.show()

print("\nALL TASKS COMPLETED ✅")

from google.colab import files
files.download("task1_wordcloud.png")